//import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import SecondNav from "@/components/secondNav";
import MetaInjector from "@/components/metaInjector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "SEDS Antariksh",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MetaInjector />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
       {/* Mobile Navbar */}
        <div className="fixed top-0 left-0 w-full z-[4000] flex lg:hidden">
          <Navbar />
        </div>

        {/* Desktop Navbar */}
        <div className="fixed top-0 left-0 w-full z-[4000] hidden lg:flex">
          <SecondNav />
        </div>

        {/* Page Content with padding to avoid overlap */}
        <main className="pt-20"> 
          {children}
        </main>
        {/* {children} */}
      </body>
    </html>
  );
}
