//import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import SecondNav from "@/components/secondNav";
// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://sedsantariksh.com"),
  title: {
    default: "SEDS Antariksh VIT Chennai — India's Premier Student Space Organization | Space Research & Astronomy",
    template: "%s | SEDS Antariksh VIT Chennai",
  },
  description: "Join India's leading student space community at VIT Chennai. Discover cutting-edge space projects, astronomy research, satellite missions, and rocket development opportunities. Connect with like-minded space enthusiasts and launch your career in aerospace.",
  keywords: ["SEDS", "Antariksh", "VIT Chennai", "space club", "astronomy", "aerospace engineering", "student space organization", "satellite projects", "rocket development", "space research", "India space", "ISRO", "space technology", "astrophysics", "space missions"],
  openGraph: {
    title: "SEDS Antariksh VIT Chennai — India's Premier Student Space Organization",
    description: "Join India's leading student space community at VIT Chennai. Discover cutting-edge space projects, astronomy research, and aerospace opportunities.",
    url: "https://sedsantariksh.com",
    siteName: "SEDS Antariksh VIT Chennai",
    images: ["/og/SEDS.jpg"],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "SEDS Antariksh VIT Chennai — India's Premier Student Space Organization",
    description: "Join India's leading student space community at VIT Chennai. Discover cutting-edge space projects, astronomy research, and aerospace opportunities.",
    images: ["/og/SEDS.jpg"],
  },
  robots: {
    index: true,
    follow: true,
  },
};




// export const metadata: Metadata = {
//   title: "SEDS Antariksh",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
         
       {/* Mobile Navbar */}
        <div className="fixed top-0 left-0 w-full z-[4000] flex lg:hidden">
          <Navbar />
        </div>

        {/* Desktop Navbar */}
        <div className="fixed top-0 left-0 w-full z-[4000] hidden lg:flex">
          <SecondNav />
        </div>

        {/* Page Content with padding to avoid overlap */}
        <main className="pt-20"> 
          {children}
        </main>
        {/* {children} */}
      </body>
    </html>
  );
}
